### ISSUE TITLE
Batch ImportError

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/BatchProfiler#26]
I saw many instances of this error below from [Batch #63](http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=63&first_item=201&page_size=25), though unfortunately the job status simply said "SUBMITTED".
They were fixed by resubmitting within BatchProfiler.

Batch file [here](https://imageweb.broadinstitute.org/imaging/analysis/2014_07_11_MitochondrialMotility_SchwarzLab_BCH/2016_02_12_dose_response_full/output/021216_doseresponse/Batch_data.h5)

An example .err file can be found here, the same as below:
https://imageweb.broadinstitute.org/imaging/analysis/2014_07_11_MitochondrialMotility_SchwarzLab_BCH/2016_02_12_dose_response_full/output/021216_doseresponse/txt_output/run.80.10.err

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/JobStatus.py", line 29, in <module>
    from RunBatch import BPJob, BPJobTask, BPTaskHost, BPJobTaskStatus, \
  File "/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/RunBatch.py", line 23, in <module>
    import bputilities
  File "/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/bputilities.py", line 4, in <module>
    import numpy as np
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/JobStatus.py", line 29, in <module>
    from RunBatch import BPJob, BPJobTask, BPTaskHost, BPJobTaskStatus, \
  File "/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/RunBatch.py", line 23, in <module>
    import bputilities
  File "/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/bputilities.py", line 4, in <module>
    import numpy as np
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
```

**Comment by LeeKamentsky** [comment]
If this was intermittent, it's most likely a network problem. The missing library is /usr/lib64/atlas/liblapack.so.3. If you look at the logs, uger-c011 and uger-c015 error-out until task ID 48 (run.80.xx.txt has size 83 and run.80.xx.err has size 0) and after that, everything works. That points to an intermittent file problem on these two machines outside of the control of BatchProfiler.
