### ISSUE TITLE
prokaryote error

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/BatchProfiler#27]
The newest build doesn't work because prokaryote isn't there

**Comment by LeeKamentsky** [comment]
I will hand-build it if you give me the git hash for the version you are running.

**Comment by jhung0** [comment]
Well at this point it's fine if I use an older version... just wanted you to know

**Comment by dlogan** [comment]
I would like this too.
Nightly, built on BatchProfiler yields:

```
Set home to /imaging/docs/People/imageweb
Running xvfb-run -n 115 python CellProfiler.py -c -r -b --do-not-fetch -p /cmap/imaging/drug_repurposing_CP/illum/output_nightly_2016_04_01/Batch_data.h5 -f 1 -l 3456 -o /cmap/imaging/drug_repurposing_CP/illum/output_nightly_2016_04_01 on uger-c016.broadinstitute.org
Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160401122119_d12088fa315f9359ef517d9f6dcf26dafb693c13/cellprofiler/__main__.py", line 181, in main
    cp_start_vm()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160401122119_d12088fa315f9359ef517d9f6dcf26dafb693c13/cellprofiler/utilities/cpjvm.py", line 159, in cp_start_vm
    class_path = get_jars()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160401122119_d12088fa315f9359ef517d9f6dcf26dafb693c13/cellprofiler/utilities/cpjvm.py", line 69, in get_jars
    imagej_path = get_path_to_jars()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160401122119_d12088fa315f9359ef517d9f6dcf26dafb693c13/cellprofiler/utilities/cpjvm.py", line 20, in get_path_to_jars
    import prokaryote
ImportError: No module named prokaryote
OK
```

**Comment by LeeKamentsky** [comment]
This should work on recent CellProfiler commits and I've updated the imagewebrhel6 website with the latest.
