### ISSUE TITLE
BatchProfiler won't build CP 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/BatchProfiler#28]
Load this: http://imagewebrhel6/batchprofiler/cgi-bin/NewBatch.py?email=dlogan@broadinstitute.org&queue=short&priority=100&project=imaging&batch_size=10&memory_limit=2000&revision=2.1.1&data_dir=/imaging/analysis/2010_05_18_Malaria_Liver_Infection_Bhatia_Lab/images/2016_03_15&write_data=no#input_data_dir

Click on Revision: "Use b65341ce..." button to load the proper CP version
Click on Build CellProfiler button.

Just reports "Building..." and never shows the popup 
@bethac07

**Comment by dlogan** [comment]
The batch output file was overwritten with CP 2.1.1, so I need to update this with a new CP version to test.

**Comment by dlogan** [comment]
- Load [this BatchProfiler page](http://imagewebrhel6/batchprofiler/cgi-bin/NewBatch.py?data_dir=%2Fimaging%2Fdocs%2FPeople%2Fdlogan%2Ftmp).
- Click the "Use fae..." button to select the proper recent CP version.  
- Click the "BuildCellProfiler" button.  It hangs.

BUT I noticed in 
 /imaging/docs/People/imageweb/.batchprofiler.sh which it seems is the correct config file, the database password is incorrect.  I tried fixing it, but then I get a database access error (see below).  Help @0x00B1 ?

```
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/NewBatch.py in ()
     29 from bputilities import *
     30 from bpformdata import *
=>   31 import RunBatch
     32 from StyleSheet import BATCHPROFILER_DOCTYPE, BATCHPROFILER_STYLE
     33 import email.message
RunBatch undefined
 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/RunBatch.py in ()
     60         connect_params[k] = v
     61         
=>   62 connection = MySQLdb.Connect(**connect_params)
     63 
     64 class bpcursor(object):
connection undefined, MySQLdb = None, MySQLdb.Connect undefined, connect_params = None
 /imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/__init__.py in Connect(*args=(), **kwargs={'db': 'batchprofiler', 'host': '10.4.0.32', 'passwd': '{cPus3r}', 'user': 'imageweb'})
     79     """Factory function for connections.Connection."""
     80     from connections import Connection
=>   81     return Connection(*args, **kwargs)
     82 
     83 connect = Connection = Connect
Connection = <class 'MySQLdb.connections.Connection'>, args = (), kwargs = {'db': 'batchprofiler', 'host': '10.4.0.32', 'passwd': '{cPus3r}', 'user': 'imageweb'}
 /imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py in __init__(self=<_mysql.connection closed at 6957bf0>, *args=(), **kwargs={'db': 'batchprofiler', 'host': '10.4.0.32', 'passwd': '{cPus3r}', 'user': 'imageweb'})
    185         kwargs2['client_flag'] = client_flag
    186 
=>  187         super(Connection, self).__init__(*args, **kwargs2)
    188 
    189         self.encoders = dict([ (k, v) for k, v in conv.items()
builtin super = <type 'super'>, global Connection = <class 'MySQLdb.connections.Connection'>, self = <_mysql.connection closed at 6957bf0>, ).__init__ = <bound method Connection.__init__ of <_mysql.connection closed at 6957bf0>>, args = (), kwargs2 = {'client_flag': 196608, 'conv': {0: <class 'decimal.Decimal'>, 1: <type 'int'>, 2: <type 'int'>, 3: <type 'long'>, 4: <type 'float'>, 5: <type 'float'>, 7: <function mysql_timestamp_converter>, 8: <type 'long'>, 9: <type 'int'>, 10: <function Date_or_None>, ...}, 'db': 'batchprofiler', 'host': '10.4.0.32', 'passwd': '{cPus3r}', 'user': 'imageweb'}
<class '_mysql_exceptions.OperationalError'>: (1045, "Access denied for user 'imageweb'@'69.173.70.131' (using password: YES)") 
      args = (1045, "Access denied for user 'imageweb'@'69.173.70.131' (using password: YES)") 
      message = ''
```

**Comment by 0x00b1** [comment]
I'll into into this. :smile:

**Comment by dlogan** [comment]
@0x00B1 Can you take a look? I need to build a recent version of CP, since it uses a ReassignObjects bugfix from the last month and BatchProfiler just times out.  Can I do this manually somehow here? /imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6

**Comment by dlogan** [comment]
On the page linked below, I click the button "Use 293..." and it just says "Building..." and nothing happens.  A popup should appear saying "Built successfully" or "Already built"

[NewBatch](http://imagewebrhel6/batchprofiler/cgi-bin/NewBatch.py?data_dir=%2Fimaging%2Fanalysis%2F2015_07_14_RSV_SyncytiaQuantification_SteffenJaensch_Janssen%2F2016_02_01_phenix%2Fanalysis3)

**Comment by dlogan** [comment]
Click on any txt output file from [Batch 145](http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=145).  It retrieves this:

```
Set home to /imaging/docs/People/imageweb
Running xvfb-run -n 102 python CellProfiler.py -c -r -b --do-not-fetch -p /imaging/analysis/2015_07_14_RSV_SyncytiaQuantification_SteffenJaensch_Janssen/2016_02_01_phenix/analysis2/Batch_data.h5 -f 1 -l 1232 -o /imaging/analysis/2015_07_14_RSV_SyncytiaQuantification_SteffenJaensch_Janssen/2016_02_01_phenix/analysis2 on uger-c044.broadinstitute.org
Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302210837_1b13225259b90a6eaddbfa2bd21326a2b8a2e7a3/cellprofiler/__main__.py", line 176, in main
    cp_start_vm()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302210837_1b13225259b90a6eaddbfa2bd21326a2b8a2e7a3/cellprofiler/utilities/cpjvm.py", line 165, in cp_start_vm
    class_path = get_jars()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302210837_1b13225259b90a6eaddbfa2bd21326a2b8a2e7a3/cellprofiler/utilities/cpjvm.py", line 78, in get_jars
    imagej_path = get_path_to_jars()
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302210837_1b13225259b90a6eaddbfa2bd21326a2b8a2e7a3/cellprofiler/utilities/cpjvm.py", line 31, in get_path_to_jars
    import prokaryote
ImportError: No module named prokaryote
OK
```

**Comment by braymp** [comment]
Same error as this issue: https://github.com/CellProfiler/BatchProfiler/issues/27#issuecomment-204652024
